export const novelsContent = {
  novels: [
    {
      id: "1",
      title: "తెలంగాణ మట్టి వాసన",
      subtitle: "గ్రామీణ జీవితపు కథల సంకలనం",
      description:
        "తెలంగాణ గ్రామాలలోని సాధారణ ప్రజల జీవితాలను, వారి కష్టనష్టాలను, సంతోషదుఃఖాలను చిత్రించిన కథల సంకలనం. ప్రతి కథ మన మట్టి వాసనతో, మన సంస్కృతితో నిండి ఉంది.",
      fullDescription:
        "ఈ నవల తెలంగాణ రాష్ట్రంలోని గ్రామీణ జీవితాన్ని వర్ణిస్తుంది. రైతుల కష్టాలు, కుటుంబ బంధాలు, సంప్రదాయాలు, మరియు ఆధునికతకు మధ్య జరిగే సంఘర్షణలను ఈ కథల ద్వారా చెప్పాను. ప్రతి పాత్ర మన చుట్టూ కనిపించే వ్యక్తులే, వారి సమస్యలు మనకు తెలిసినవే.",
      coverImage: "/placeholder.svg?height=400&width=300&text=తెలంగాణ+మట్టి+వాసన",
      publishedDate: "2010-03-15",
      pages: 280,
      publisher: "తెలుగు సాహిత్య ప్రకాశన్",
      isbn: "978-81-234-5678-9",
      price: {
        paperback: 250,
        ebook: 150,
      },
      genre: "గ్రామీణ కథలు",
      language: "తెలుగు",
      awards: ["తెలంగాణ రాష్ట్ర సాహిత్య అకాడమీ అవార్డు - 2015"],
      rating: 4.5,
      reviews: 156,
      featured: true,
      available: true,
      purchaseLinks: {
        amazon: "https://amazon.in/telangana-matti-vasana",
        flipkart: "https://flipkart.com/telangana-matti-vasana",
        publisher: "https://telugusahitya.com/books/telangana-matti-vasana",
      },
      excerpt: "గ్రామంలో పుట్టి పెరిగిన వాడిని పట్టణంలో చూస్తే, అతని కళ్లల్లో ఎప్పుడూ ఒక వేదన కనిపిస్తుంది. అది తన మూలాలను వదిలి వచ్చిన వేదన...",
    },
    {
      id: "2",
      title: "కాలం మారిపోయింది",
      subtitle: "ఆధునిక యువత మరియు సంప్రదాయాల మధ్య",
      description: "మారుతున్న కాలంలో యువత ఎదుర్కొనే సవాళ్లు, వారి కలలు, ఆకాంక్షలు మరియు సంప్రదాయాలతో వారికున్న సంబంధం గురించిన నవల.",
      fullDescription:
        "ఈ నవలలో ఆధునిక యువత ఎదుర్కొనే సమస్యలను వర్ణించాను. విద్య, ఉద్యోగం, పెళ్లి, కుటుంబ బాధ్యతలు - ఇవన్నీ కలిసి యువతను ఎలా ప్రభావితం చేస్తున్నాయో చెప్పాను. అదే సమయంలో మన సంప్రదాయాలను ఎలా కాపాడుకోవాలో కూడా చర్చించాను.",
      coverImage: "/placeholder.svg?height=400&width=300&text=కాలం+మారిపోయింది",
      publishedDate: "2018-08-20",
      pages: 320,
      publisher: "ఆంధ్ర ప్రదేశ్ సాహిత్య అకాడమీ",
      isbn: "978-81-234-5679-6",
      price: {
        paperback: 300,
        ebook: 180,
      },
      genre: "సామాజిక నవల",
      language: "తెలుగు",
      awards: [],
      rating: 4.2,
      reviews: 89,
      featured: true,
      available: true,
      purchaseLinks: {
        amazon: "https://amazon.in/kalam-maripoyindi",
        flipkart: "https://flipkart.com/kalam-maripoyindi",
        publisher: "https://apsahityaakademi.com/books/kalam-maripoyindi",
      },
      excerpt: "నేటి యువత చాలా గందరగోళంలో ఉంది. ఒకవైపు ఆధునికత, మరోవైపు సంప్రదాయాలు. ఈ రెండింటి మధ్య సమతుల్యం దొరకడం చాలా కష్టం...",
    },
    {
      id: "3",
      title: "అమ్మ",
      subtitle: "ప్రేమ, త్యాగం మరియు మమకారం",
      description: "అమ్మ అనే మాట వింటే మనసులో కలిగే భావాలను, అమ్మ ప్రేమ యొక్క గొప్పతనాన్ని చెప్పే హృదయస్పర్శీ నవల.",
      fullDescription:
        "ఈ నవల అమ్మ ప్రేమ గురించి. ఒక అమ్మ తన పిల్లల కోసం ఎంత త్యాగం చేస్తుందో, ఎంత కష్టపడుతుందో చెప్పాను. అదే సమయంలో పిల్లలు పెద్దయ్యాక అమ్మను ఎలా మర్చిపోతారో కూడా చూపించాను. ఇది ప్రతి కుటుంబంలో జరిగే కథ.",
      coverImage: "/placeholder.svg?height=400&width=300&text=అమ్మ",
      publishedDate: "2021-05-10",
      pages: 240,
      publisher: "విశాఖ పబ్లికేషన్స్",
      isbn: "978-81-234-5680-2",
      price: {
        paperback: 220,
        ebook: 120,
      },
      genre: "కుటుంబ నవల",
      language: "తెలుగు",
      awards: ["జిల్లా స్థాయి సాహిత్య పురస్కారం - 2022"],
      rating: 4.7,
      reviews: 203,
      featured: false,
      available: true,
      purchaseLinks: {
        amazon: "https://amazon.in/amma-novel",
        flipkart: "https://flipkart.com/amma-novel",
        publisher: "https://visakhabooks.com/amma",
      },
      excerpt: "అమ్మ అంటే ప్రేమ, అమ్మ అంటే త్యాగం, అమ్మ అంటే మమకారం. ఈ మూడూ లేని జీవితం ఎంత శూన్యమో తెలుసుకోవాలంటే...",
    },
    {
      id: "4",
      title: "గ్రామం నుండి నగరానికి",
      subtitle: "వలస జీవితం మరియు కలలు",
      description: "ఉద్యోగం కోసం గ్రామం నుండి నగరానికి వచ్చిన యువకుల జీవితం, వారు ఎదుర్కొనే సమస్యలు మరియు విజయాల కథ.",
      fullDescription:
        "ఈ నవలలో గ్రామం నుండి నగరానికి వలస వచ్చిన యువకుల కథ చెప్పాను. వారి కష్టాలు, కలలు, నిరాశలు, విజయాలు - అన్నీ ఉన్నాయి. నగర జీవితంలో తమ గుర్తింపు కోసం పోరాడుతున్న వారి కథ ఇది.",
      coverImage: "/placeholder.svg?height=400&width=300&text=గ్రామం+నుండి+నగరానికి",
      publishedDate: "2023-11-25",
      pages: 360,
      publisher: "హైదరాబాద్ బుక్ హౌస్",
      isbn: "978-81-234-5681-9",
      price: {
        paperback: 350,
        ebook: 200,
      },
      genre: "సామాజిక నవల",
      language: "తెలుగు",
      awards: [],
      rating: 4.3,
      reviews: 67,
      featured: false,
      available: true,
      purchaseLinks: {
        amazon: "https://amazon.in/gramam-nundi-nagaraniki",
        flipkart: "https://flipkart.com/gramam-nundi-nagaraniki",
        publisher: "https://hyderabadbookhouse.com/gramam-nundi-nagaraniki",
      },
      excerpt: "గ్రామంలో పుట్టిన కలలు నగరంలో నెరవేరుతాయా? లేక నగర జీవితంలో కరిగిపోతాయా? ఈ ప్రశ్నకు సమాధానం వెతుక్కుంటూ...",
    },
  ],
  stats: {
    totalNovels: 4,
    totalPages: 1200,
    totalReaders: 15000,
    averageRating: 4.4,
  },
}
